services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      # Add other environment variables as needed

  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    staticPublishPath: src/build
